a
%CREATEFIGURE(YMATRIX1,YMATRIX2)
%  YMATRIX1:  matrix of y data
%  YMATRIX2:  matrix of y data

%  Auto-generated by MATLAB on 19-Jul-2016 09:44:49

% Create figure
figure1 = figure;

% Create subplot
subplot1 = subplot(2,1,1,'Parent',figure1);
box(subplot1,'on');
hold(subplot1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(YMatrix1,'Parent',subplot1);
set(plot1(1),'DisplayName','Close');
set(plot1(2),'DisplayName','lag');
set(plot1(3),'DisplayName','lead');

% Create xlabel
xlabel({'Daily Sample',''});

% Create ylabel
ylabel('Price');

% Create title
title('Bund Closing Price');

% Create subplot
subplot2 = subplot(2,1,2,'Parent',figure1);
box(subplot2,'on');
grid(subplot2,'on');
hold(subplot2,'all');

% Create ylabel
ylabel({'Return',''});

% Create multiple lines using matrix input to plot
plot2 = plot(YMatrix2,'Parent',subplot2);
set(plot2(1),'DisplayName','r');
set(plot2(2),'DisplayName','w');

